// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuDmV7EPoNVKdY5G34pi9JHXdZYYddPCI',
    appId: '1:676706541474:web:6e095d49b3526a6dc61cfb',
    messagingSenderId: '676706541474',
    projectId: 'chat-duo-f8aa3',
    authDomain: 'chat-duo-f8aa3.firebaseapp.com',
    storageBucket: 'chat-duo-f8aa3.appspot.com',
    measurementId: 'G-ZZWJTVDN0R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4HO8ILjYj_8nR_mGaLjneR34Yoz02eos',
    appId: '1:676706541474:android:12483b99570af437c61cfb',
    messagingSenderId: '676706541474',
    projectId: 'chat-duo-f8aa3',
    storageBucket: 'chat-duo-f8aa3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA9mzPwkuuqoKJe-9Nd97YXCO3bWIPbY4',
    appId: '1:676706541474:ios:cd832023fbf88bd9c61cfb',
    messagingSenderId: '676706541474',
    projectId: 'chat-duo-f8aa3',
    storageBucket: 'chat-duo-f8aa3.appspot.com',
    iosBundleId: 'com.ashmawi.chatDuo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA9mzPwkuuqoKJe-9Nd97YXCO3bWIPbY4',
    appId: '1:676706541474:ios:cd832023fbf88bd9c61cfb',
    messagingSenderId: '676706541474',
    projectId: 'chat-duo-f8aa3',
    storageBucket: 'chat-duo-f8aa3.appspot.com',
    iosBundleId: 'com.ashmawi.chatDuo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuDmV7EPoNVKdY5G34pi9JHXdZYYddPCI',
    appId: '1:676706541474:web:08d022c1f54df38bc61cfb',
    messagingSenderId: '676706541474',
    projectId: 'chat-duo-f8aa3',
    authDomain: 'chat-duo-f8aa3.firebaseapp.com',
    storageBucket: 'chat-duo-f8aa3.appspot.com',
    measurementId: 'G-43WV572F1S',
  );
}
